'use strict';
const $=id=>document.getElementById(id), KEY='marble_workshop_pro_v7';
let holes=[], edges={top:'مستقيم',right:'مستقيم',bottom:'مستقيم',left:'مستقيم'}, pieces=[], currentId=null, deferredPrompt=null;
const num=id=>Math.max(0,Number($(id)?.value)||0), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function polygonMetrics(poly){let area=0,per=0;for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length];area+=a[0]*b[1]-b[0]*a[1];per+=Math.hypot(b[0]-a[0],b[1]-a[1])}return {area:Math.abs(area)/2,per}}
function shapeData(){const L=num('length'),W=num('width'),S=$('shape').value,a=num('lArm'),b=num('lLeg'),t=num('uThick');let area=0,per=0,poly=null;
 if(S==='circle'){const r=Math.min(L,W)/2;area=Math.PI*r*r;per=2*Math.PI*r}
 else if(S==='semi'){const r=L/2;area=Math.PI*r*r/2;per=Math.PI*r+2*r;poly=null}
 else if(S==='L'){if(a>0&&b>0&&a<L&&b<W){poly=[[0,0],[L,0],[L,W-b],[L-a,W-b],[L-a,W],[0,W]];({area,per}=polygonMetrics(poly))}}
 else if(S==='U'){if(t>0&&2*t<L&&t<W){poly=[[0,0],[L,0],[L,W],[L-t,W],[L-t,t],[t,t],[t,W],[0,W]];({area,per}=polygonMetrics(poly))}}
 else {area=L*W;per=2*(L+W);poly=[[0,0],[L,0],[L,W],[0,W]]}
 return {L,W,S,a,b,t,area:area/1e6,per:per/1000,poly};}
function holeInfo(h){let x=numv(h.x),y=numv(h.y);if(h.type==='circle'){let r=numv(h.r);return {area:Math.PI*r*r,box:{x:x-r,y:y-r,w:2*r,d:2*r},label:`Ø${2*r} مم`}}let w=numv(h.w),d=numv(h.d);return {area:w*d,box:{x,y,w,d},label:`${w} × ${d} مم`}}
function numv(v){return Math.max(0,Number(v)||0)}
function pointInShape(x,y,g){if(x<0||y<0||x>g.L||y>g.W)return false;if(g.S==='L')return !(x>g.L-g.a&&y>g.W-g.b);if(g.S==='U'){let t=g.t;return !(x>t&&x<g.L-t&&y>t)}if(g.S==='circle'){const r=Math.min(g.L,g.W)/2;return Math.hypot(x-g.L/2,y-g.W/2)<=r+1e-9}if(g.S==='semi'){const r=g.L/2;return y>=-1e-9&&Math.hypot(x-r,y)<=r+1e-9}return true}
function holeInsideShape(h,g){const z=holeInfo(h),q=z.box,pts=[];if(h.type==='circle'){for(let i=0;i<32;i++){const a=2*Math.PI*i/32;pts.push([numv(h.x)+numv(h.r)*Math.cos(a),numv(h.y)+numv(h.r)*Math.sin(a)])}pts.push([numv(h.x),numv(h.y)])}else{for(let ix=0;ix<=4;ix++)for(let iy=0;iy<=4;iy++)pts.push([q.x+q.w*ix/4,q.y+q.d*iy/4])}return pts.every(p=>pointInShape(p[0],p[1],g))}
function validate(g){let e=[];if(g.L<=0||g.W<=0)e.push('الطول والعرض يجب أن يكونا أكبر من صفر.');if(num('thickness')<=0)e.push('السماكة يجب أن تكون أكبر من صفر.');if(g.S==='L'&&(g.a<=0||g.b<=0||g.a>=g.L||g.b>=g.W))e.push('أبعاد L غير صالحة.');if(g.S==='circle'&&Math.abs(g.L-g.W)>0.001)e.push('الدائرة يجب أن تكون بأبعاد متساوية.');if(g.S==='semi'&&Math.abs(g.L-2*g.W)>0.001)e.push('نصف الدائرة يتطلب الطول = ضعف العرض (القطر = الطول).');if(g.S==='U'&&(num('uThick')<=0||2*num('uThick')>=g.L||num('uThick')>=g.W))e.push('سماكة شكل U غير صالحة.');if(num('waste')>100)e.push('الهدر يجب ألا يتجاوز 100%.');
 const boxes=[];holes.forEach((h,i)=>{const z=holeInfo(h),q=z.box;if(q.w<=0||q.d<=0)e.push(`الفتحة ${i+1}: المقاس غير صالح.`);if(!holeInsideShape(h,g))e.push(`الفتحة ${i+1}: خارج حدود القطعة أو شكلها.`);boxes.push(q)});
 for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){let A=boxes[i],B=boxes[j];if(A.x<B.x+B.w&&A.x+A.w>B.x&&A.y<B.y+B.d&&A.y+A.d>B.y)e.push(`الفتحتان ${i+1} و${j+1} متداخلتان.`)}return [...new Set(e)]}
function calc(){const g=shapeData(),errors=validate(g);const holeArea=holes.reduce((s,h)=>s+holeInfo(h).area,0)/1e6;const net=Math.max(0,g.area-holeArea), waste=num('waste'), buy=net*(1+waste/100), cost=buy*num('price');
 $('gross').textContent=g.area.toFixed(3);$('cut').textContent=holeArea.toFixed(3);$('net').textContent=net.toFixed(3);$('linear').textContent=g.per.toFixed(2);$('withWaste').textContent=buy.toFixed(3)+' م²';$('cost').textContent=cost.toFixed(2);$('perimeter').textContent=g.per.toFixed(2)+' م';$('thicknessOut').textContent=num('thickness')+' مم';
 const v=$('validation');v.className='validation '+(errors.length?'':'okbox');v.innerHTML=errors.length?errors.map(esc).join('<br>'):'القطعة صالحة هندسياً ضمن القواعد الحالية.';draw(g,errors);return {g,holeArea,net,buy,cost,errors}}
function svgText(x,y,text,size=14,anchor='middle'){return `<text x="${x}" y="${y}" font-size="${size}" text-anchor="${anchor}" font-family="Tahoma,Arial">${esc(text)}</text>`}
function draw(g,errors){const vw=1100,vh=700,p=115,scale=Math.min((vw-2*p)/Math.max(g.L,1),(vh-2*p)/Math.max(g.W,1)),x=p,y=vh-p-g.W*scale,cx=x+g.L*scale/2,cy=y+g.W*scale/2;let shape='';
 if(g.S==='circle'){let r=Math.min(g.L,g.W)/2*scale;shape=`<circle cx="${cx}" cy="${cy}" r="${r}" fill="#eef2f6" stroke="#0b1f3a" stroke-width="3"/>`}
 else if(g.S==='semi'){let r=g.L/2*scale,base=y+g.W*scale;shape=`<path d="M${x} ${base} A${r} ${r} 0 0 1 ${x+g.L*scale} ${base} L${x} ${base}Z" fill="#eef2f6" stroke="#0b1f3a" stroke-width="3"/>`}
 else if(g.S==='L'){let a=g.a*scale,b=g.b*scale;shape=`<path d="M${x} ${y}H${x+g.L*scale}V${y+(g.W-g.b)*scale}H${x+(g.L-g.a)*scale}V${y+g.W*scale}H${x}Z" fill="#eef2f6" stroke="#0b1f3a" stroke-width="3"/>`}
 else if(g.S==='U'){let t=num('uThick')*scale;shape=`<path d="M${x} ${y}H${x+g.L*scale}V${y+g.W*scale}H${x+g.L*scale-t}V${y+t}H${x+t}V${y+g.W*scale}H${x}Z" fill="#eef2f6" stroke="#0b1f3a" stroke-width="3"/>`}
 else shape=`<rect x="${x}" y="${y}" width="${g.L*scale}" height="${g.W*scale}" rx="${g.S==='curve'?Math.min(70,g.W*scale/4):0}" fill="#eef2f6" stroke="#0b1f3a" stroke-width="3"/>`;
 let hs='';holes.forEach((h,i)=>{let z=holeInfo(h);if(h.type==='circle'){hs+=`<circle cx="${x+numv(h.x)*scale}" cy="${y+g.W*scale-numv(h.y)*scale}" r="${numv(h.r)*scale}" fill="none" stroke="#b42318" stroke-width="3"/>${svgText(x+numv(h.x)*scale,y+g.W*scale-(numv(h.y)+numv(h.r))*scale-8,`فتحة ${i+1} ${z.label}`,12)}`}else{hs+=`<rect x="${x+numv(h.x)*scale}" y="${y+g.W*scale-(numv(h.y)+numv(h.d))*scale}" width="${numv(h.w)*scale}" height="${numv(h.d)*scale}" fill="none" stroke="#b42318" stroke-width="3"/>${svgText(x+(numv(h.x)+numv(h.w)/2)*scale,y+g.W*scale-(numv(h.y)+numv(h.d)/2)*scale,z.label,12)}`}});
 const note=errors.length?'⚠ لا يعتمد المخطط للقص حتى إصلاح الأخطاء':'مخطط تصنيع مساعد — راجع المقاسات الميدانية قبل القص';$('drawing').innerHTML=`<svg viewBox="0 0 ${vw} ${vh}" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%" fill="white"/>${svgText(vw/2,30,$('projectName').value||'قطعة بدون اسم',22)}${svgText(vw/2,55,`${$('pieceType').value} — ${$('material').value} — سماكة ${num('thickness')} مم`,13)}${shape}${hs}<line x1="${x}" y1="${y-35}" x2="${x+g.L*scale}" y2="${y-35}" stroke="#555"/><line x1="${x}" y1="${y-42}" x2="${x}" y2="${y-28}" stroke="#555"/><line x1="${x+g.L*scale}" y1="${y-42}" x2="${x+g.L*scale}" y2="${y-28}" stroke="#555"/>${svgText(cx,y-48,`${g.L} مم`,16)}<line x1="${x-35}" y1="${y}" x2="${x-35}" y2="${y+g.W*scale}" stroke="#555"/><line x1="${x-42}" y1="${y}" x2="${x-28}" y2="${y}" stroke="#555"/><line x1="${x-42}" y1="${y+g.W*scale}" x2="${x-28}" y2="${y+g.W*scale}" stroke="#555"/>${svgText(x-48,y+g.W*scale/2,`${g.W} مم`,16)}${svgText(25,vh-18,note,12,'start')}</svg>`}
function renderHoles(){const b=$('holes');b.innerHTML='';holes.forEach((h,i)=>{const d=document.createElement('div');d.className='hole';d.innerHTML=`<div class="holegrid"><select data-i="${i}" data-k="type"><option value="rect" ${h.type==='rect'?'selected':''}>مستطيلة</option><option value="circle" ${h.type==='circle'?'selected':''}>دائرية</option></select><input data-i="${i}" data-k="x" type="number" min="0" step="1" placeholder="X مم" value="${h.x??0}"><input data-i="${i}" data-k="y" type="number" min="0" step="1" placeholder="Y مم" value="${h.y??0}"><input data-i="${i}" data-k="w" type="number" min="0" step="1" placeholder="العرض مم" value="${h.w??0}"><input data-i="${i}" data-k="d" type="number" min="0" step="1" placeholder="العمق مم" value="${h.d??0}"><input data-i="${i}" data-k="r" type="number" min="0" step="1" placeholder="نصف القطر مم" value="${h.r??0}"></div><button class="danger" data-del="${i}">حذف</button>`;b.appendChild(d)});b.querySelectorAll('[data-i]').forEach(el=>el.addEventListener('input',()=>{holes[+el.dataset.i][el.dataset.k]=el.value;calc()}));b.querySelectorAll('[data-del]').forEach(el=>el.onclick=()=>{holes.splice(+el.dataset.del,1);renderHoles();calc()})}
function projectData(){return {id:currentId||crypto.randomUUID(),version:7,fields:Object.fromEntries(['projectName','pieceType','material','shape','thickness','length','width','price','waste','notes','lArm','lLeg','uThick'].map(k=>[k,$(k).value])),holes:structuredClone(holes),edges:structuredClone(edges),pieces:structuredClone(pieces),updatedAt:new Date().toISOString()}}
function load(o){currentId=o.id||crypto.randomUUID();Object.entries(o.fields||{}).forEach(([k,v])=>$(k)&&( $(k).value=v));holes=Array.isArray(o.holes)?o.holes:[];edges=o.edges||edges;pieces=o.pieces||[];renderHoles();renderPieces();calc();$('status').textContent='تم فتح المشروع محلياً.'}
function getProjects(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function listProjects(){const a=getProjects().sort((x,y)=>String(y.updatedAt).localeCompare(String(x.updatedAt)));$('projects').innerHTML=a.length?a.map(p=>`<div class="project"><span>${esc(p.fields?.projectName||'بدون اسم')} — ${esc(p.fields?.pieceType||'')}</span><span><button class="secondary" data-load="${esc(p.id)}">فتح</button> <button class="danger" data-remove="${esc(p.id)}">حذف</button></span></div>`).join(''):'لا توجد مشاريع محفوظة.';$('projects').querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{const p=a.find(x=>x.id===b.dataset.load);if(p)load(p)});$('projects').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(confirm('حذف المشروع من الجهاز؟')){localStorage.setItem(KEY,JSON.stringify(a.filter(x=>x.id!==b.dataset.remove)));listProjects()}})}
function save(){const r=calc();if(r.errors.length){$('status').className='status error';$('status').textContent='لم يتم الحفظ: أصلح أخطاء القياسات.';return}const o=projectData(),a=getProjects(),i=a.findIndex(x=>x.id===o.id);i>=0?a[i]=o:a.unshift(o);localStorage.setItem(KEY,JSON.stringify(a));currentId=o.id;listProjects();$('status').className='status success';$('status').textContent='تم الحفظ محلياً.'}
function fresh(){currentId=null;['projectName','notes'].forEach(k=>$(k).value='');$('pieceType').value='مجلى';$('material').value='رخام';$('shape').value='rect';$('thickness').value=20;$('length').value=2000;$('width').value=600;$('price').value=0;$('waste').value=10;$('lArm').value=350;$('lLeg').value=350;$('uThick').value=200;holes=[];pieces=[];renderHoles();renderPieces();calc()}
function renderPieces(){const el=$('pieceList');if(!el)return;el.innerHTML=pieces.length?pieces.map((p,i)=>`<div class="project"><span>${i+1}. ${esc(p.name||'قطعة')} — ${p.L}×${p.W} مم</span><button class="danger" data-pdel="${i}">حذف</button></div>`).join(''):'لا توجد قطع في اللوح.';el.querySelectorAll('[data-pdel]').forEach(b=>b.onclick=()=>{pieces.splice(+b.dataset.pdel,1);renderPieces();})}
function optimize(){const SL=num('slabL'),SW=num('slabW'),gap=num('kerf'),arr=pieces.map(p=>({...p})).filter(p=>p.L>0&&p.W>0);let x=0,y=0,rowH=0,placed=[],failed=[];arr.sort((a,b)=>b.L*b.W-a.L*a.W).forEach((p,i)=>{let opts=[{w:p.L,h:p.W,r:false},{w:p.W,h:p.L,r:true}];let chosen=null;for(const o of opts){if(x+o.w<=SL&&y+o.h<=SW){chosen=o;break}}if(!chosen){x=0;y+=rowH+gap;rowH=0;for(const o of opts){if(x+o.w<=SL&&y+o.h<=SW){chosen=o;break}}}if(chosen){placed.push({...p,x,y,w:chosen.w,h:chosen.h,rotated:chosen.r});x+=chosen.w+gap;rowH=Math.max(rowH,chosen.h)}else failed.push(p)});const usedArea=placed.reduce((s,p)=>s+p.w*p.h,0)/1e6,total=SL*SW/1e6,waste=Math.max(0,total-usedArea);$('nestResult').innerHTML=`<b>المستعمل:</b> ${usedArea.toFixed(3)} م² &nbsp; <b>الهدر الهندسي:</b> ${waste.toFixed(3)} م² &nbsp; <b>فشل الإدراج:</b> ${failed.length}`;drawSlab(placed,SL,SW,failed)}
function drawSlab(ps,SL,SW,failed){const vw=1000,vh=620,p=60,s=Math.min((vw-2*p)/SL,(vh-2*p)/SW),x=p,y=p;let body=`<rect x="${x}" y="${y}" width="${SL*s}" height="${SW*s}" fill="#f5f7f9" stroke="#0b1f3a" stroke-width="3"/>`;ps.forEach((q,i)=>{body+=`<rect x="${x+q.x*s}" y="${y+q.y*s}" width="${q.w*s}" height="${q.h*s}" fill="#dfe7ef" stroke="#0b1f3a"/><text x="${x+(q.x+q.w/2)*s}" y="${y+(q.y+q.h/2)*s}" text-anchor="middle" dominant-baseline="middle" font-size="13">${esc(q.name||'قطعة')}<tspan x="${x+(q.x+q.w/2)*s}" dy="16">${q.w}×${q.h}</tspan></text>`});$('slabDrawing').innerHTML=`<svg viewBox="0 0 ${vw} ${vh}" xmlns="http://www.w3.org/2000/svg">${body}</svg>`;if(failed.length)$('nestStatus').textContent='تعذر وضع بعض القطع. جرّب لوحاً أكبر أو ترتيباً مختلفاً.';else $('nestStatus').textContent='تم إيجاد توزيع أولي للقطع. راجع اتجاه العروق ومسار القص.'}
function dxfPair(code,value){return `${code}\n${value}\n`}
function exportDXF(){const r=calc();if(r.errors.length){$('status').className='status error';$('status').textContent='لا يمكن تصدير DXF قبل إصلاح الأخطاء.';return}const g=r.g;let d='0\nSECTION\n2\nENTITIES\n';const addLine=(x1,y1,x2,y2)=>{d+='0\nLINE\n8\nCUT\n'+dxfPair(10,x1)+dxfPair(20,y1)+dxfPair(11,x2)+dxfPair(21,y2)};if(g.S==='circle'){d+='0\nCIRCLE\n8\nCUT\n'+dxfPair(10,g.L/2)+dxfPair(20,g.W/2)+dxfPair(40,g.L/2)}else if(g.S==='semi'){addLine(0,0,g.L,0);d+='0\nARC\n8\nCUT\n'+dxfPair(10,g.L/2)+dxfPair(20,0)+dxfPair(40,g.L/2)+dxfPair(50,0)+dxfPair(51,180)}else if(g.poly){for(let i=0;i<g.poly.length;i++){const a=g.poly[i],b=g.poly[(i+1)%g.poly.length];addLine(a[0],a[1],b[0],b[1])}}else{addLine(0,0,g.L,0);addLine(g.L,0,g.L,g.W);addLine(g.L,g.W,0,g.W);addLine(0,g.W,0,0)}holes.forEach(h=>{if(h.type==='circle')d+='0\nCIRCLE\n8\nHOLES\n'+dxfPair(10,h.x)+dxfPair(20,h.y)+dxfPair(40,h.r);else{const x=h.x,y=h.y,w=h.w,z=h.d;addLine(x,y,x+w,y);addLine(x+w,y,x+w,y+z);addLine(x+w,y+z,x,y+z);addLine(x,y+z,x,y)}});d+='0\nENDSEC\n0\nEOF\n';const blob=new Blob([d],{type:'application/dxf'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=(($('projectName').value||'marble-piece').replace(/[^a-zA-Z0-9_-]+/g,'_'))+'.dxf';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
$('addHole').onclick=()=>{holes.push({type:'rect',x:50,y:50,w:100,d:100,r:50});renderHoles();calc()};document.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',calc));$('saveBtn').onclick=save;$('newBtn').onclick=()=>confirm('بدء مشروع جديد؟')&&fresh();$('dxfBtn')&&($('dxfBtn').onclick=exportDXF);$('printBtn').onclick=()=>{const r=calc();if(!r.errors.length)window.print()};$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({app:'MarbleFabricationPro',version:7,exportedAt:new Date().toISOString(),projects:getProjects()},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='marble-workshop-backup-v7.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};$('importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.projects))throw 0;localStorage.setItem(KEY,JSON.stringify(d.projects));listProjects();if(d.projects[0])load(d.projects[0]);$('status').textContent='تمت الاستعادة بنجاح.'}catch{$('status').textContent='ملف النسخة الاحتياطية غير صالح.'}e.target.value=''};r.readAsText(f)};
$('addPiece').onclick=()=>{pieces.push({name:`قطعة ${pieces.length+1}`,L:num('pieceL'),W:num('pieceW')});renderPieces()};$('optimizeBtn').onclick=optimize;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')};window.addEventListener('appinstalled',()=>{$('status').className='status success';$('status').textContent='تم تثبيت التطبيق بنجاح.'});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});renderHoles();renderPieces();calc();listProjects();
